[package]
name = "sg_assistant"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
dotenv = "0.15.0"
poise = "0.6.1"
reqwest = "0.12.7"
serde = "1.0.208"
tokio = { version = "1.39.2", features = ["rt-multi-thread"] }
