services:
  sg_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sg_app
    env_file:
      - .env
    dns:
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped
